#!/usr/bin/env bash

LIB_OPENAL="$1"
JAVA_BIN="$2"
LEGACY_LAUNCHER_JAR_PATH="$3"

shift 3

export __GL_THREADED_OPTIMIZATIONS=0
export LD_PRELOAD=$LD_PRELOAD:$LIB_OPENAL
"$JAVA_BIN" -jar "$LEGACY_LAUNCHER_JAR_PATH" "$@"
